# -*- coding: UTF-8 -*-
# Code automatically generated by pycrate_asn1c

from pycrate_asn1rt.utils            import *
from pycrate_asn1rt.err              import *
from pycrate_asn1rt.glob             import make_GLOBAL, GLOBAL
from pycrate_asn1rt.dictobj          import ASN1Dict
from pycrate_asn1rt.refobj           import *
from pycrate_asn1rt.setobj           import *
from pycrate_asn1rt.asnobj_basic     import *
from pycrate_asn1rt.asnobj_str       import *
from pycrate_asn1rt.asnobj_construct import *
from pycrate_asn1rt.asnobj_class     import *
from pycrate_asn1rt.asnobj_ext       import *
from pycrate_asn1rt.init             import init_modules

class KapschOps1955Message:

    _name_  = 'KapschOps1955Message'
    _oid_   = []
    
    _obj_ = [
        'Octetstring',
        'Container',
        'Action-Request',
        'Action-Confirmation',
        'Attribute',
        'Attribute-List',
        'Set-Request',
        'Set-Confirmation',
        'Attribute-ID-List',
        'Get-Request',
        'Get-Confirmation',
        'Application',
        'Application-List',
        'OBE-Configuration',
        'Notify-Application-Beacon',
        'Ready-Application',
        'Notify-Application-Lost-Message',
        'Forced-Release',
        'Tis-Ready-Application',
        'TRX-Status',
        'TRX-ID',
        'TRX-Internal-Humidity',
        'TRX-Internal-Temperature',
        'TRX-My-Power-Mode',
        'TRX-Carrier-Frequency',
        'TRX-Uplink-Parameters',
        'TRX-Output-Power',
        'TRX-Echo',
        'UI-Control-OPS1925',
        'UI-Control-OPS1955',
        'TRX-Set-UI-Control',
        'TRX-Read-UI-Control',
        'TRX-UI-Status',
        'TRX-General-Purpose',
        'TRX-Extended-Output-Power',
        'TRX-Set-RF-Param',
        'TRX-Read-RF-Param',
        'Lic-Nalm-Behaviour',
        'Lic-PDU-No-Behaviour',
        'Lic-L7-Ack-Mode',
        'Lic-Private-Uplink-Window-Time',
        'Lic-Slow-Data-Behaviour',
        'Lic-Release-Retransmissions',
        'Lic-LID-Cleanup-Mode',
        'DSRC-Link-Mode',
        'DSRC-Configuration',
        'Beacon-ID',
        'BST-Configuration',
        'Time',
        'General-Log-Level',
        'Log-Category-Mode',
        'Transaction-Status',
        'Echo',
        'Communication-Log-Result',
        'LiC-Status',
        'LiC-Statistics',
        'Status-Mode',
        'LiC-Version',
        'Ops1955-Message-Types',
        ]
    _type_ = [
        'Octetstring',
        'Container',
        'Action-Request',
        'Action-Confirmation',
        'Attribute',
        'Attribute-List',
        'Set-Request',
        'Set-Confirmation',
        'Attribute-ID-List',
        'Get-Request',
        'Get-Confirmation',
        'Application',
        'Application-List',
        'OBE-Configuration',
        'Notify-Application-Beacon',
        'Ready-Application',
        'Notify-Application-Lost-Message',
        'Forced-Release',
        'Tis-Ready-Application',
        'TRX-Status',
        'TRX-ID',
        'TRX-Internal-Humidity',
        'TRX-Internal-Temperature',
        'TRX-My-Power-Mode',
        'TRX-Carrier-Frequency',
        'TRX-Uplink-Parameters',
        'TRX-Output-Power',
        'TRX-Echo',
        'UI-Control-OPS1925',
        'UI-Control-OPS1955',
        'TRX-Set-UI-Control',
        'TRX-Read-UI-Control',
        'TRX-UI-Status',
        'TRX-General-Purpose',
        'TRX-Extended-Output-Power',
        'TRX-Set-RF-Param',
        'TRX-Read-RF-Param',
        'Lic-Nalm-Behaviour',
        'Lic-PDU-No-Behaviour',
        'Lic-L7-Ack-Mode',
        'Lic-Private-Uplink-Window-Time',
        'Lic-Slow-Data-Behaviour',
        'Lic-Release-Retransmissions',
        'Lic-LID-Cleanup-Mode',
        'DSRC-Link-Mode',
        'DSRC-Configuration',
        'Beacon-ID',
        'BST-Configuration',
        'Time',
        'General-Log-Level',
        'Log-Category-Mode',
        'Transaction-Status',
        'Echo',
        'Communication-Log-Result',
        'LiC-Status',
        'LiC-Statistics',
        'Status-Mode',
        'LiC-Version',
        'Ops1955-Message-Types',
        ]
    _set_ = [
        ]
    _val_ = [
        ]
    _class_ = [
        ]
    _param_ = [
        ]
    
    #-----< Octetstring >-----#
    Octetstring = SEQ(name='Octetstring', mode=MODE_TYPE)
    _Octetstring_no_of_octets = INT(name='no-of-octets', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Octetstring_octet = SEQ_OF(name='octet', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __Octetstring_octet__item_ = OCT_STR(name='_item_', mode=MODE_TYPE)
    _Octetstring_octet._cont = __Octetstring_octet__item_
    _Octetstring_octet._const_sz = ASN1Set(rv=[127], rr=[], ev=None, er=[])
    Octetstring._cont = ASN1Dict([
        ('no-of-octets', _Octetstring_no_of_octets),
        ('octet', _Octetstring_octet),
        ])
    Octetstring._ext = None
    
    #-----< Container >-----#
    Container = CHOICE(name='Container', mode=MODE_TYPE)
    _Container_integer = INT(name='integer', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Container_octetstring = SEQ(name='octetstring', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Octetstring')))
    Container._cont = ASN1Dict([
        ('integer', _Container_integer),
        ('octetstring', _Container_octetstring),
        ])
    Container._ext = None
    
    #-----< Action-Request >-----#
    Action_Request = SEQ(name='Action-Request', mode=MODE_TYPE)
    _Action_Request_flow_control_priority = INT(name='flow-control-priority', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Action_Request_link_id = INT(name='link-id', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Action_Request_flow_control = INT(name='flow-control', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Action_Request_access_credentials_bit_map = BOOL(name='access-credentials-bit-map', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Action_Request_action_parameter_bit_map = BOOL(name='action-parameter-bit-map', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Action_Request_mode = BOOL(name='mode', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Action_Request_element_id = INT(name='element-id', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Action_Request_access_credentials = SEQ(name='access-credentials', mode=MODE_TYPE, tag=(7, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Octetstring')))
    _Action_Request_action_parameter = CHOICE(name='action-parameter', mode=MODE_TYPE, tag=(8, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Container')))
    Action_Request._cont = ASN1Dict([
        ('flow-control-priority', _Action_Request_flow_control_priority),
        ('link-id', _Action_Request_link_id),
        ('flow-control', _Action_Request_flow_control),
        ('access-credentials-bit-map', _Action_Request_access_credentials_bit_map),
        ('action-parameter-bit-map', _Action_Request_action_parameter_bit_map),
        ('mode', _Action_Request_mode),
        ('element-id', _Action_Request_element_id),
        ('access-credentials', _Action_Request_access_credentials),
        ('action-parameter', _Action_Request_action_parameter),
        ])
    Action_Request._ext = None
    
    #-----< Action-Confirmation >-----#
    Action_Confirmation = SEQ(name='Action-Confirmation', mode=MODE_TYPE)
    _Action_Confirmation_link_id = INT(name='link-id', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Action_Confirmation_response_parameter_bit_map = BOOL(name='response-parameter-bit-map', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Action_Confirmation_return_status_bit_map = BOOL(name='return-status-bit-map', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Action_Confirmation_element_id = INT(name='element-id', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Action_Confirmation_response_parameter = CHOICE(name='response-parameter', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Container')))
    _Action_Confirmation_return_status = INT(name='return-status', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Action_Confirmation_instance = INT(name='instance', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Action_Confirmation._cont = ASN1Dict([
        ('link-id', _Action_Confirmation_link_id),
        ('response-parameter-bit-map', _Action_Confirmation_response_parameter_bit_map),
        ('return-status-bit-map', _Action_Confirmation_return_status_bit_map),
        ('element-id', _Action_Confirmation_element_id),
        ('response-parameter', _Action_Confirmation_response_parameter),
        ('return-status', _Action_Confirmation_return_status),
        ('instance', _Action_Confirmation_instance),
        ])
    Action_Confirmation._ext = None
    
    #-----< Attribute >-----#
    Attribute = SEQ(name='Attribute', mode=MODE_TYPE)
    _Attribute_attribute_id = INT(name='attribute-id', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Attribute_attribute_choice = INT(name='attribute-choice', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Attribute_container = CHOICE(name='container', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_EXPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Container')))
    Attribute._cont = ASN1Dict([
        ('attribute-id', _Attribute_attribute_id),
        ('attribute-choice', _Attribute_attribute_choice),
        ('container', _Attribute_container),
        ])
    Attribute._ext = None
    
    #-----< Attribute-List >-----#
    Attribute_List = SEQ(name='Attribute-List', mode=MODE_TYPE)
    _Attribute_List_no_of_attributes = INT(name='no-of-attributes', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Attribute_List_attribute = SEQ_OF(name='attribute', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __Attribute_List_attribute__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('KapschOps1955Message', 'Attribute')))
    _Attribute_List_attribute._cont = __Attribute_List_attribute__item_
    _Attribute_List_attribute._const_sz = ASN1Set(rv=[16], rr=[], ev=None, er=[])
    Attribute_List._cont = ASN1Dict([
        ('no-of-attributes', _Attribute_List_no_of_attributes),
        ('attribute', _Attribute_List_attribute),
        ])
    Attribute_List._ext = None
    
    #-----< Set-Request >-----#
    Set_Request = SEQ(name='Set-Request', mode=MODE_TYPE)
    _Set_Request_flow_control_priority = INT(name='flow-control-priority', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Set_Request_link_id = INT(name='link-id', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Set_Request_flow_control = INT(name='flow-control', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Set_Request_access_credentials_bit_map = BOOL(name='access-credentials-bit-map', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Set_Request_mode = BOOL(name='mode', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Set_Request_element_id = INT(name='element-id', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Set_Request_access_credentials = SEQ(name='access-credentials', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Octetstring')))
    _Set_Request_attribute_list = SEQ(name='attribute-list', mode=MODE_TYPE, tag=(7, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Attribute-List')))
    Set_Request._cont = ASN1Dict([
        ('flow-control-priority', _Set_Request_flow_control_priority),
        ('link-id', _Set_Request_link_id),
        ('flow-control', _Set_Request_flow_control),
        ('access-credentials-bit-map', _Set_Request_access_credentials_bit_map),
        ('mode', _Set_Request_mode),
        ('element-id', _Set_Request_element_id),
        ('access-credentials', _Set_Request_access_credentials),
        ('attribute-list', _Set_Request_attribute_list),
        ])
    Set_Request._ext = None
    
    #-----< Set-Confirmation >-----#
    Set_Confirmation = SEQ(name='Set-Confirmation', mode=MODE_TYPE)
    _Set_Confirmation_link_id = INT(name='link-id', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Set_Confirmation_return_status_bit_map = BOOL(name='return-status-bit-map', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Set_Confirmation_element_id = INT(name='element-id', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Set_Confirmation_return_status = INT(name='return-status', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Set_Confirmation_instance = INT(name='instance', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Set_Confirmation._cont = ASN1Dict([
        ('link-id', _Set_Confirmation_link_id),
        ('return-status-bit-map', _Set_Confirmation_return_status_bit_map),
        ('element-id', _Set_Confirmation_element_id),
        ('return-status', _Set_Confirmation_return_status),
        ('instance', _Set_Confirmation_instance),
        ])
    Set_Confirmation._ext = None
    
    #-----< Attribute-ID-List >-----#
    Attribute_ID_List = SEQ(name='Attribute-ID-List', mode=MODE_TYPE)
    _Attribute_ID_List_no_of_attribute_ids = INT(name='no-of-attribute-ids', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Attribute_ID_List_attribute_id = SEQ_OF(name='attribute-id', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __Attribute_ID_List_attribute_id__item_ = INT(name='_item_', mode=MODE_TYPE)
    _Attribute_ID_List_attribute_id._cont = __Attribute_ID_List_attribute_id__item_
    _Attribute_ID_List_attribute_id._const_sz = ASN1Set(rv=[16], rr=[], ev=None, er=[])
    Attribute_ID_List._cont = ASN1Dict([
        ('no-of-attribute-ids', _Attribute_ID_List_no_of_attribute_ids),
        ('attribute-id', _Attribute_ID_List_attribute_id),
        ])
    Attribute_ID_List._ext = None
    
    #-----< Get-Request >-----#
    Get_Request = SEQ(name='Get-Request', mode=MODE_TYPE)
    _Get_Request_flow_control_priority = INT(name='flow-control-priority', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Get_Request_link_id = INT(name='link-id', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Get_Request_flow_control = INT(name='flow-control', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Get_Request_access_credentials_bit_map = BOOL(name='access-credentials-bit-map', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Get_Request_element_id = INT(name='element-id', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Get_Request_access_credentials = SEQ(name='access-credentials', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Octetstring')))
    _Get_Request_attribute_id_list = SEQ(name='attribute-id-list', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Attribute-ID-List')))
    Get_Request._cont = ASN1Dict([
        ('flow-control-priority', _Get_Request_flow_control_priority),
        ('link-id', _Get_Request_link_id),
        ('flow-control', _Get_Request_flow_control),
        ('access-credentials-bit-map', _Get_Request_access_credentials_bit_map),
        ('element-id', _Get_Request_element_id),
        ('access-credentials', _Get_Request_access_credentials),
        ('attribute-id-list', _Get_Request_attribute_id_list),
        ])
    Get_Request._ext = None
    
    #-----< Get-Confirmation >-----#
    Get_Confirmation = SEQ(name='Get-Confirmation', mode=MODE_TYPE)
    _Get_Confirmation_link_id = INT(name='link-id', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Get_Confirmation_attribute_list_bit_map = BOOL(name='attribute-list-bit-map', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Get_Confirmation_return_status_bit_map = BOOL(name='return-status-bit-map', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Get_Confirmation_element_id = INT(name='element-id', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Get_Confirmation_attribute_list = SEQ(name='attribute-list', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Attribute-List')))
    _Get_Confirmation_return_status = INT(name='return-status', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Get_Confirmation_instance = INT(name='instance', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Get_Confirmation._cont = ASN1Dict([
        ('link-id', _Get_Confirmation_link_id),
        ('attribute-list-bit-map', _Get_Confirmation_attribute_list_bit_map),
        ('return-status-bit-map', _Get_Confirmation_return_status_bit_map),
        ('element-id', _Get_Confirmation_element_id),
        ('attribute-list', _Get_Confirmation_attribute_list),
        ('return-status', _Get_Confirmation_return_status),
        ('instance', _Get_Confirmation_instance),
        ])
    Get_Confirmation._ext = None
    
    #-----< Application >-----#
    Application = SEQ(name='Application', mode=MODE_TYPE)
    _Application_element_id_bit_map = BOOL(name='element-id-bit-map', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Application_parameter_bit_map = BOOL(name='parameter-bit-map', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Application_application_id = INT(name='application-id', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Application_element_id = INT(name='element-id', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Application_parameter = SEQ(name='parameter', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Octetstring')))
    Application._cont = ASN1Dict([
        ('element-id-bit-map', _Application_element_id_bit_map),
        ('parameter-bit-map', _Application_parameter_bit_map),
        ('application-id', _Application_application_id),
        ('element-id', _Application_element_id),
        ('parameter', _Application_parameter),
        ])
    Application._ext = None
    
    #-----< Application-List >-----#
    Application_List = SEQ(name='Application-List', mode=MODE_TYPE)
    _Application_List_no_of_applications = INT(name='no-of-applications', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Application_List_application = SEQ_OF(name='application', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __Application_List_application__item_ = SEQ(name='_item_', mode=MODE_TYPE, typeref=ASN1RefType(('KapschOps1955Message', 'Application')))
    _Application_List_application._cont = __Application_List_application__item_
    _Application_List_application._const_sz = ASN1Set(rv=[4], rr=[], ev=None, er=[])
    Application_List._cont = ASN1Dict([
        ('no-of-applications', _Application_List_no_of_applications),
        ('application', _Application_List_application),
        ])
    Application_List._ext = None
    
    #-----< OBE-Configuration >-----#
    OBE_Configuration = SEQ(name='OBE-Configuration', mode=MODE_TYPE)
    _OBE_Configuration_equipment_class = INT(name='equipment-class', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _OBE_Configuration_manufacturer_id = INT(name='manufacturer-id', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _OBE_Configuration_obe_status = INT(name='obe-status', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    OBE_Configuration._cont = ASN1Dict([
        ('equipment-class', _OBE_Configuration_equipment_class),
        ('manufacturer-id', _OBE_Configuration_manufacturer_id),
        ('obe-status', _OBE_Configuration_obe_status),
        ])
    OBE_Configuration._ext = None
    
    #-----< Notify-Application-Beacon >-----#
    Notify_Application_Beacon = SEQ(name='Notify-Application-Beacon', mode=MODE_TYPE)
    _Notify_Application_Beacon_trx_no = INT(name='trx-no', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Notify_Application_Beacon_link_id = INT(name='link-id', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Notify_Application_Beacon_application_list = SEQ(name='application-list', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Application-List')))
    _Notify_Application_Beacon_obe_configuration = SEQ(name='obe-configuration', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'OBE-Configuration')))
    Notify_Application_Beacon._cont = ASN1Dict([
        ('trx-no', _Notify_Application_Beacon_trx_no),
        ('link-id', _Notify_Application_Beacon_link_id),
        ('application-list', _Notify_Application_Beacon_application_list),
        ('obe-configuration', _Notify_Application_Beacon_obe_configuration),
        ])
    Notify_Application_Beacon._ext = None
    
    #-----< Ready-Application >-----#
    Ready_Application = SEQ(name='Ready-Application', mode=MODE_TYPE)
    _Ready_Application_flow_control_priority = INT(name='flow-control-priority', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Ready_Application_application_id = INT(name='application-id', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Ready_Application_link_id = INT(name='link-id', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Ready_Application._cont = ASN1Dict([
        ('flow-control-priority', _Ready_Application_flow_control_priority),
        ('application-id', _Ready_Application_application_id),
        ('link-id', _Ready_Application_link_id),
        ])
    Ready_Application._ext = None
    
    #-----< Notify-Application-Lost-Message >-----#
    Notify_Application_Lost_Message = SEQ(name='Notify-Application-Lost-Message', mode=MODE_TYPE)
    _Notify_Application_Lost_Message_link_id = INT(name='link-id', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Notify_Application_Lost_Message_value = INT(name='value', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Notify_Application_Lost_Message._cont = ASN1Dict([
        ('link-id', _Notify_Application_Lost_Message_link_id),
        ('value', _Notify_Application_Lost_Message_value),
        ])
    Notify_Application_Lost_Message._ext = None
    
    #-----< Forced-Release >-----#
    Forced_Release = SEQ(name='Forced-Release', mode=MODE_TYPE)
    _Forced_Release_application_id = INT(name='application-id', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Forced_Release_link_id = INT(name='link-id', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Forced_Release._cont = ASN1Dict([
        ('application-id', _Forced_Release_application_id),
        ('link-id', _Forced_Release_link_id),
        ])
    Forced_Release._ext = None
    
    #-----< Tis-Ready-Application >-----#
    Tis_Ready_Application = SEQ(name='Tis-Ready-Application', mode=MODE_TYPE)
    _Tis_Ready_Application_flow_control_priority = INT(name='flow-control-priority', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Tis_Ready_Application_application_id = INT(name='application-id', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Tis_Ready_Application_link_id = INT(name='link-id', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Tis_Ready_Application_eid = INT(name='eid', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Tis_Ready_Application._cont = ASN1Dict([
        ('flow-control-priority', _Tis_Ready_Application_flow_control_priority),
        ('application-id', _Tis_Ready_Application_application_id),
        ('link-id', _Tis_Ready_Application_link_id),
        ('eid', _Tis_Ready_Application_eid),
        ])
    Tis_Ready_Application._ext = None
    
    #-----< TRX-Status >-----#
    TRX_Status = SEQ(name='TRX-Status', mode=MODE_TYPE)
    _TRX_Status_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Status_status = SEQ_OF(name='status', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __TRX_Status_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _TRX_Status_status._cont = __TRX_Status_status__item_
    _TRX_Status_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _TRX_Status_trx_mode = INT(name='trx-mode', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    TRX_Status._cont = ASN1Dict([
        ('instance', _TRX_Status_instance),
        ('status', _TRX_Status_status),
        ('trx-mode', _TRX_Status_trx_mode),
        ])
    TRX_Status._ext = None
    
    #-----< TRX-ID >-----#
    TRX_ID = SEQ(name='TRX-ID', mode=MODE_TYPE)
    _TRX_ID_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_ID_status = SEQ_OF(name='status', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __TRX_ID_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _TRX_ID_status._cont = __TRX_ID_status__item_
    _TRX_ID_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _TRX_ID_trx_id = SEQ_OF(name='trx-id', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __TRX_ID_trx_id__item_ = INT(name='_item_', mode=MODE_TYPE)
    _TRX_ID_trx_id._cont = __TRX_ID_trx_id__item_
    _TRX_ID_trx_id._const_sz = ASN1Set(rv=[8], rr=[], ev=None, er=[])
    _TRX_ID_hwid = SEQ_OF(name='hwid', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __TRX_ID_hwid__item_ = INT(name='_item_', mode=MODE_TYPE)
    _TRX_ID_hwid._cont = __TRX_ID_hwid__item_
    _TRX_ID_hwid._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _TRX_ID_swid = SEQ_OF(name='swid', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __TRX_ID_swid__item_ = INT(name='_item_', mode=MODE_TYPE)
    _TRX_ID_swid._cont = __TRX_ID_swid__item_
    _TRX_ID_swid._const_sz = ASN1Set(rv=[3], rr=[], ev=None, er=[])
    TRX_ID._cont = ASN1Dict([
        ('instance', _TRX_ID_instance),
        ('status', _TRX_ID_status),
        ('trx-id', _TRX_ID_trx_id),
        ('hwid', _TRX_ID_hwid),
        ('swid', _TRX_ID_swid),
        ])
    TRX_ID._ext = None
    
    #-----< TRX-Internal-Humidity >-----#
    TRX_Internal_Humidity = SEQ(name='TRX-Internal-Humidity', mode=MODE_TYPE)
    _TRX_Internal_Humidity_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Internal_Humidity_status = SEQ_OF(name='status', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __TRX_Internal_Humidity_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _TRX_Internal_Humidity_status._cont = __TRX_Internal_Humidity_status__item_
    _TRX_Internal_Humidity_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _TRX_Internal_Humidity_humid = INT(name='humid', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    TRX_Internal_Humidity._cont = ASN1Dict([
        ('instance', _TRX_Internal_Humidity_instance),
        ('status', _TRX_Internal_Humidity_status),
        ('humid', _TRX_Internal_Humidity_humid),
        ])
    TRX_Internal_Humidity._ext = None
    
    #-----< TRX-Internal-Temperature >-----#
    TRX_Internal_Temperature = SEQ(name='TRX-Internal-Temperature', mode=MODE_TYPE)
    _TRX_Internal_Temperature_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Internal_Temperature_status = SEQ_OF(name='status', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __TRX_Internal_Temperature_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _TRX_Internal_Temperature_status._cont = __TRX_Internal_Temperature_status__item_
    _TRX_Internal_Temperature_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _TRX_Internal_Temperature_temp = INT(name='temp', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    TRX_Internal_Temperature._cont = ASN1Dict([
        ('instance', _TRX_Internal_Temperature_instance),
        ('status', _TRX_Internal_Temperature_status),
        ('temp', _TRX_Internal_Temperature_temp),
        ])
    TRX_Internal_Temperature._ext = None
    
    #-----< TRX-My-Power-Mode >-----#
    TRX_My_Power_Mode = SEQ(name='TRX-My-Power-Mode', mode=MODE_TYPE)
    _TRX_My_Power_Mode_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_My_Power_Mode_mode = INT(name='mode', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    TRX_My_Power_Mode._cont = ASN1Dict([
        ('instance', _TRX_My_Power_Mode_instance),
        ('mode', _TRX_My_Power_Mode_mode),
        ])
    TRX_My_Power_Mode._ext = None
    
    #-----< TRX-Carrier-Frequency >-----#
    TRX_Carrier_Frequency = SEQ(name='TRX-Carrier-Frequency', mode=MODE_TYPE)
    _TRX_Carrier_Frequency_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Carrier_Frequency_status = SEQ_OF(name='status', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    __TRX_Carrier_Frequency_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _TRX_Carrier_Frequency_status._cont = __TRX_Carrier_Frequency_status__item_
    _TRX_Carrier_Frequency_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _TRX_Carrier_Frequency_cfq = INT(name='cfq', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    TRX_Carrier_Frequency._cont = ASN1Dict([
        ('instance', _TRX_Carrier_Frequency_instance),
        ('status', _TRX_Carrier_Frequency_status),
        ('cfq', _TRX_Carrier_Frequency_cfq),
        ])
    TRX_Carrier_Frequency._ext = None
    
    #-----< TRX-Uplink-Parameters >-----#
    TRX_Uplink_Parameters = SEQ(name='TRX-Uplink-Parameters', mode=MODE_TYPE)
    _TRX_Uplink_Parameters_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Uplink_Parameters_upl = INT(name='upl', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    TRX_Uplink_Parameters._cont = ASN1Dict([
        ('instance', _TRX_Uplink_Parameters_instance),
        ('upl', _TRX_Uplink_Parameters_upl),
        ])
    TRX_Uplink_Parameters._ext = None
    
    #-----< TRX-Output-Power >-----#
    TRX_Output_Power = SEQ(name='TRX-Output-Power', mode=MODE_TYPE)
    _TRX_Output_Power_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Output_Power_status = SEQ_OF(name='status', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    __TRX_Output_Power_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _TRX_Output_Power_status._cont = __TRX_Output_Power_status__item_
    _TRX_Output_Power_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _TRX_Output_Power_spw = INT(name='spw', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    TRX_Output_Power._cont = ASN1Dict([
        ('instance', _TRX_Output_Power_instance),
        ('status', _TRX_Output_Power_status),
        ('spw', _TRX_Output_Power_spw),
        ])
    TRX_Output_Power._ext = None
    
    #-----< TRX-Echo >-----#
    TRX_Echo = SEQ(name='TRX-Echo', mode=MODE_TYPE)
    _TRX_Echo_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Echo_data = OCT_STR(name='data', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Echo_data._const_sz = ASN1Set(rv=[122], rr=[], ev=None, er=[])
    _TRX_Echo_length = INT(name='length', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    TRX_Echo._cont = ASN1Dict([
        ('instance', _TRX_Echo_instance),
        ('data', _TRX_Echo_data),
        ('length', _TRX_Echo_length),
        ])
    TRX_Echo._ext = None
    
    #-----< UI-Control-OPS1925 >-----#
    UI_Control_OPS1925 = SEQ(name='UI-Control-OPS1925', mode=MODE_TYPE)
    _UI_Control_OPS1925_mode = INT(name='mode', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _UI_Control_OPS1925_green_led = INT(name='green-led', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _UI_Control_OPS1925_orange_led = INT(name='orange-led', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _UI_Control_OPS1925_red_led = INT(name='red-led', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    UI_Control_OPS1925._cont = ASN1Dict([
        ('mode', _UI_Control_OPS1925_mode),
        ('green-led', _UI_Control_OPS1925_green_led),
        ('orange-led', _UI_Control_OPS1925_orange_led),
        ('red-led', _UI_Control_OPS1925_red_led),
        ])
    UI_Control_OPS1925._ext = None
    
    #-----< UI-Control-OPS1955 >-----#
    UI_Control_OPS1955 = SEQ(name='UI-Control-OPS1955', mode=MODE_TYPE)
    _UI_Control_OPS1955_red = INT(name='red', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _UI_Control_OPS1955_green = INT(name='green', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _UI_Control_OPS1955_blue = INT(name='blue', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    UI_Control_OPS1955._cont = ASN1Dict([
        ('red', _UI_Control_OPS1955_red),
        ('green', _UI_Control_OPS1955_green),
        ('blue', _UI_Control_OPS1955_blue),
        ])
    UI_Control_OPS1955._ext = None
    
    #-----< TRX-Set-UI-Control >-----#
    TRX_Set_UI_Control = SEQ(name='TRX-Set-UI-Control', mode=MODE_TYPE)
    _TRX_Set_UI_Control_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Set_UI_Control_status = SEQ_OF(name='status', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    __TRX_Set_UI_Control_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _TRX_Set_UI_Control_status._cont = __TRX_Set_UI_Control_status__item_
    _TRX_Set_UI_Control_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _TRX_Set_UI_Control_uitype = INT(name='uitype', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Set_UI_Control_ops1925 = SEQ(name='ops1925', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'UI-Control-OPS1925')), opt=True)
    _TRX_Set_UI_Control_ops1955 = SEQ(name='ops1955', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'UI-Control-OPS1955')), opt=True)
    TRX_Set_UI_Control._cont = ASN1Dict([
        ('instance', _TRX_Set_UI_Control_instance),
        ('status', _TRX_Set_UI_Control_status),
        ('uitype', _TRX_Set_UI_Control_uitype),
        ('ops1925', _TRX_Set_UI_Control_ops1925),
        ('ops1955', _TRX_Set_UI_Control_ops1955),
        ])
    TRX_Set_UI_Control._ext = None
    
    #-----< TRX-Read-UI-Control >-----#
    TRX_Read_UI_Control = SEQ(name='TRX-Read-UI-Control', mode=MODE_TYPE)
    _TRX_Read_UI_Control_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Read_UI_Control_status = SEQ_OF(name='status', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    __TRX_Read_UI_Control_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _TRX_Read_UI_Control_status._cont = __TRX_Read_UI_Control_status__item_
    _TRX_Read_UI_Control_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _TRX_Read_UI_Control_uitype = INT(name='uitype', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Read_UI_Control_mode = INT(name='mode', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _TRX_Read_UI_Control_ops1925 = SEQ(name='ops1925', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'UI-Control-OPS1925')), opt=True)
    _TRX_Read_UI_Control_ops1955 = SEQ(name='ops1955', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'UI-Control-OPS1955')), opt=True)
    TRX_Read_UI_Control._cont = ASN1Dict([
        ('instance', _TRX_Read_UI_Control_instance),
        ('status', _TRX_Read_UI_Control_status),
        ('uitype', _TRX_Read_UI_Control_uitype),
        ('mode', _TRX_Read_UI_Control_mode),
        ('ops1925', _TRX_Read_UI_Control_ops1925),
        ('ops1955', _TRX_Read_UI_Control_ops1955),
        ])
    TRX_Read_UI_Control._ext = None
    
    #-----< TRX-UI-Status >-----#
    TRX_UI_Status = SEQ(name='TRX-UI-Status', mode=MODE_TYPE)
    _TRX_UI_Status_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_UI_Status_status = SEQ_OF(name='status', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    __TRX_UI_Status_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _TRX_UI_Status_status._cont = __TRX_UI_Status_status__item_
    _TRX_UI_Status_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _TRX_UI_Status_uitype = INT(name='uitype', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _TRX_UI_Status_sensors = INT(name='sensors', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    TRX_UI_Status._cont = ASN1Dict([
        ('instance', _TRX_UI_Status_instance),
        ('status', _TRX_UI_Status_status),
        ('uitype', _TRX_UI_Status_uitype),
        ('sensors', _TRX_UI_Status_sensors),
        ])
    TRX_UI_Status._ext = None
    
    #-----< TRX-General-Purpose >-----#
    TRX_General_Purpose = SEQ(name='TRX-General-Purpose', mode=MODE_TYPE)
    _TRX_General_Purpose_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_General_Purpose_password = OCT_STR(name='password', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _TRX_General_Purpose_password._const_sz = ASN1Set(rv=[8], rr=[], ev=None, er=[])
    _TRX_General_Purpose_genid = INT(name='genid', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _TRX_General_Purpose_genda_genre = OCT_STR(name='genda-genre', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _TRX_General_Purpose_genda_genre._const_sz = ASN1Set(rv=[255], rr=[], ev=None, er=[])
    _TRX_General_Purpose_status = SEQ_OF(name='status', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    __TRX_General_Purpose_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _TRX_General_Purpose_status._cont = __TRX_General_Purpose_status__item_
    _TRX_General_Purpose_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _TRX_General_Purpose_length = INT(name='length', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    TRX_General_Purpose._cont = ASN1Dict([
        ('instance', _TRX_General_Purpose_instance),
        ('password', _TRX_General_Purpose_password),
        ('genid', _TRX_General_Purpose_genid),
        ('genda-genre', _TRX_General_Purpose_genda_genre),
        ('status', _TRX_General_Purpose_status),
        ('length', _TRX_General_Purpose_length),
        ])
    TRX_General_Purpose._ext = None
    
    #-----< TRX-Extended-Output-Power >-----#
    TRX_Extended_Output_Power = SEQ(name='TRX-Extended-Output-Power', mode=MODE_TYPE)
    _TRX_Extended_Output_Power_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Extended_Output_Power_password = OCT_STR(name='password', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Extended_Output_Power_password._const_sz = ASN1Set(rv=[8], rr=[], ev=None, er=[])
    _TRX_Extended_Output_Power_spw = INT(name='spw', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    TRX_Extended_Output_Power._cont = ASN1Dict([
        ('instance', _TRX_Extended_Output_Power_instance),
        ('password', _TRX_Extended_Output_Power_password),
        ('spw', _TRX_Extended_Output_Power_spw),
        ])
    TRX_Extended_Output_Power._ext = None
    
    #-----< TRX-Set-RF-Param >-----#
    TRX_Set_RF_Param = SEQ(name='TRX-Set-RF-Param', mode=MODE_TYPE)
    _TRX_Set_RF_Param_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Set_RF_Param_password = OCT_STR(name='password', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Set_RF_Param_password._const_sz = ASN1Set(rv=[8], rr=[], ev=None, er=[])
    _TRX_Set_RF_Param_id = INT(name='id', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Set_RF_Param_data = INT(name='data', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    TRX_Set_RF_Param._cont = ASN1Dict([
        ('instance', _TRX_Set_RF_Param_instance),
        ('password', _TRX_Set_RF_Param_password),
        ('id', _TRX_Set_RF_Param_id),
        ('data', _TRX_Set_RF_Param_data),
        ])
    TRX_Set_RF_Param._ext = None
    
    #-----< TRX-Read-RF-Param >-----#
    TRX_Read_RF_Param = SEQ(name='TRX-Read-RF-Param', mode=MODE_TYPE)
    _TRX_Read_RF_Param_instance = INT(name='instance', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _TRX_Read_RF_Param_password = OCT_STR(name='password', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _TRX_Read_RF_Param_password._const_sz = ASN1Set(rv=[8], rr=[], ev=None, er=[])
    _TRX_Read_RF_Param_id1 = INT(name='id1', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _TRX_Read_RF_Param_id2 = INT(name='id2', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _TRX_Read_RF_Param_data = OCT_STR(name='data', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _TRX_Read_RF_Param_data._const_sz = ASN1Set(rv=[255], rr=[], ev=None, er=[])
    _TRX_Read_RF_Param_length = INT(name='length', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    TRX_Read_RF_Param._cont = ASN1Dict([
        ('instance', _TRX_Read_RF_Param_instance),
        ('password', _TRX_Read_RF_Param_password),
        ('id1', _TRX_Read_RF_Param_id1),
        ('id2', _TRX_Read_RF_Param_id2),
        ('data', _TRX_Read_RF_Param_data),
        ('length', _TRX_Read_RF_Param_length),
        ])
    TRX_Read_RF_Param._ext = None
    
    #-----< Lic-Nalm-Behaviour >-----#
    Lic_Nalm_Behaviour = SEQ(name='Lic-Nalm-Behaviour', mode=MODE_TYPE)
    _Lic_Nalm_Behaviour_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Lic_Nalm_Behaviour_behaviour = INT(name='behaviour', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Lic_Nalm_Behaviour._cont = ASN1Dict([
        ('message-status', _Lic_Nalm_Behaviour_message_status),
        ('behaviour', _Lic_Nalm_Behaviour_behaviour),
        ])
    Lic_Nalm_Behaviour._ext = None
    
    #-----< Lic-PDU-No-Behaviour >-----#
    Lic_PDU_No_Behaviour = SEQ(name='Lic-PDU-No-Behaviour', mode=MODE_TYPE)
    _Lic_PDU_No_Behaviour_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Lic_PDU_No_Behaviour_behaviour = INT(name='behaviour', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Lic_PDU_No_Behaviour._cont = ASN1Dict([
        ('message-status', _Lic_PDU_No_Behaviour_message_status),
        ('behaviour', _Lic_PDU_No_Behaviour_behaviour),
        ])
    Lic_PDU_No_Behaviour._ext = None
    
    #-----< Lic-L7-Ack-Mode >-----#
    Lic_L7_Ack_Mode = SEQ(name='Lic-L7-Ack-Mode', mode=MODE_TYPE)
    _Lic_L7_Ack_Mode_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Lic_L7_Ack_Mode_mode = INT(name='mode', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Lic_L7_Ack_Mode._cont = ASN1Dict([
        ('message-status', _Lic_L7_Ack_Mode_message_status),
        ('mode', _Lic_L7_Ack_Mode_mode),
        ])
    Lic_L7_Ack_Mode._ext = None
    
    #-----< Lic-Private-Uplink-Window-Time >-----#
    Lic_Private_Uplink_Window_Time = SEQ(name='Lic-Private-Uplink-Window-Time', mode=MODE_TYPE)
    _Lic_Private_Uplink_Window_Time_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Lic_Private_Uplink_Window_Time_uplink_window_time = INT(name='uplink-window-time', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Lic_Private_Uplink_Window_Time._cont = ASN1Dict([
        ('message-status', _Lic_Private_Uplink_Window_Time_message_status),
        ('uplink-window-time', _Lic_Private_Uplink_Window_Time_uplink_window_time),
        ])
    Lic_Private_Uplink_Window_Time._ext = None
    
    #-----< Lic-Slow-Data-Behaviour >-----#
    Lic_Slow_Data_Behaviour = SEQ(name='Lic-Slow-Data-Behaviour', mode=MODE_TYPE)
    _Lic_Slow_Data_Behaviour_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Lic_Slow_Data_Behaviour_slow_data_behaviour = INT(name='slow-data-behaviour', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Lic_Slow_Data_Behaviour._cont = ASN1Dict([
        ('message-status', _Lic_Slow_Data_Behaviour_message_status),
        ('slow-data-behaviour', _Lic_Slow_Data_Behaviour_slow_data_behaviour),
        ])
    Lic_Slow_Data_Behaviour._ext = None
    
    #-----< Lic-Release-Retransmissions >-----#
    Lic_Release_Retransmissions = SEQ(name='Lic-Release-Retransmissions', mode=MODE_TYPE)
    _Lic_Release_Retransmissions_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Lic_Release_Retransmissions_retransmissions = INT(name='retransmissions', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Lic_Release_Retransmissions._cont = ASN1Dict([
        ('message-status', _Lic_Release_Retransmissions_message_status),
        ('retransmissions', _Lic_Release_Retransmissions_retransmissions),
        ])
    Lic_Release_Retransmissions._ext = None
    
    #-----< Lic-LID-Cleanup-Mode >-----#
    Lic_LID_Cleanup_Mode = SEQ(name='Lic-LID-Cleanup-Mode', mode=MODE_TYPE)
    _Lic_LID_Cleanup_Mode_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Lic_LID_Cleanup_Mode_lid_cleanup_mode = INT(name='lid-cleanup-mode', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Lic_LID_Cleanup_Mode._cont = ASN1Dict([
        ('message-status', _Lic_LID_Cleanup_Mode_message_status),
        ('lid-cleanup-mode', _Lic_LID_Cleanup_Mode_lid_cleanup_mode),
        ])
    Lic_LID_Cleanup_Mode._ext = None
    
    #-----< DSRC-Link-Mode >-----#
    DSRC_Link_Mode = SEQ(name='DSRC-Link-Mode', mode=MODE_TYPE)
    _DSRC_Link_Mode_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _DSRC_Link_Mode_mode = INT(name='mode', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    DSRC_Link_Mode._cont = ASN1Dict([
        ('message-status', _DSRC_Link_Mode_message_status),
        ('mode', _DSRC_Link_Mode_mode),
        ])
    DSRC_Link_Mode._ext = None
    
    #-----< DSRC-Configuration >-----#
    DSRC_Configuration = SEQ(name='DSRC-Configuration', mode=MODE_TYPE)
    _DSRC_Configuration_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _DSRC_Configuration_trx_position = INT(name='trx-position', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _DSRC_Configuration_bst_mode = INT(name='bst-mode', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _DSRC_Configuration_low_priority_bst_cycle_time = INT(name='low-priority-bst-cycle-time', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _DSRC_Configuration_high_priority_bst_cycle_time = INT(name='high-priority-bst-cycle-time', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _DSRC_Configuration_max_cycle_time_llc_retransmissions_level_1 = INT(name='max-cycle-time-llc-retransmissions-level-1', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _DSRC_Configuration_max_cycle_time_llc_retransmissions_level_2 = INT(name='max-cycle-time-llc-retransmissions-level-2', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _DSRC_Configuration_max_cycle_time_llc_retransmissions_level_3 = INT(name='max-cycle-time-llc-retransmissions-level-3', mode=MODE_TYPE, tag=(7, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _DSRC_Configuration_max_cycle_time_llc_retransmissions_level_4 = INT(name='max-cycle-time-llc-retransmissions-level-4', mode=MODE_TYPE, tag=(8, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _DSRC_Configuration_max_nr_llc_retransmissions_level_1 = INT(name='max-nr-llc-retransmissions-level-1', mode=MODE_TYPE, tag=(9, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _DSRC_Configuration_max_nr_llc_retransmissions_level_2 = INT(name='max-nr-llc-retransmissions-level-2', mode=MODE_TYPE, tag=(10, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _DSRC_Configuration_max_nr_llc_retransmissions_level_3 = INT(name='max-nr-llc-retransmissions-level-3', mode=MODE_TYPE, tag=(11, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _DSRC_Configuration_max_nr_llc_retransmissions_level_4 = INT(name='max-nr-llc-retransmissions-level-4', mode=MODE_TYPE, tag=(12, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _DSRC_Configuration_max_nr_mac_retransmissions = INT(name='max-nr-mac-retransmissions', mode=MODE_TYPE, tag=(13, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    DSRC_Configuration._cont = ASN1Dict([
        ('message-status', _DSRC_Configuration_message_status),
        ('trx-position', _DSRC_Configuration_trx_position),
        ('bst-mode', _DSRC_Configuration_bst_mode),
        ('low-priority-bst-cycle-time', _DSRC_Configuration_low_priority_bst_cycle_time),
        ('high-priority-bst-cycle-time', _DSRC_Configuration_high_priority_bst_cycle_time),
        ('max-cycle-time-llc-retransmissions-level-1', _DSRC_Configuration_max_cycle_time_llc_retransmissions_level_1),
        ('max-cycle-time-llc-retransmissions-level-2', _DSRC_Configuration_max_cycle_time_llc_retransmissions_level_2),
        ('max-cycle-time-llc-retransmissions-level-3', _DSRC_Configuration_max_cycle_time_llc_retransmissions_level_3),
        ('max-cycle-time-llc-retransmissions-level-4', _DSRC_Configuration_max_cycle_time_llc_retransmissions_level_4),
        ('max-nr-llc-retransmissions-level-1', _DSRC_Configuration_max_nr_llc_retransmissions_level_1),
        ('max-nr-llc-retransmissions-level-2', _DSRC_Configuration_max_nr_llc_retransmissions_level_2),
        ('max-nr-llc-retransmissions-level-3', _DSRC_Configuration_max_nr_llc_retransmissions_level_3),
        ('max-nr-llc-retransmissions-level-4', _DSRC_Configuration_max_nr_llc_retransmissions_level_4),
        ('max-nr-mac-retransmissions', _DSRC_Configuration_max_nr_mac_retransmissions),
        ])
    DSRC_Configuration._ext = None
    
    #-----< Beacon-ID >-----#
    Beacon_ID = SEQ(name='Beacon-ID', mode=MODE_TYPE)
    _Beacon_ID_manufacturer_id = INT(name='manufacturer-id', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Beacon_ID_individual_id = INT(name='individual-id', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Beacon_ID._cont = ASN1Dict([
        ('manufacturer-id', _Beacon_ID_manufacturer_id),
        ('individual-id', _Beacon_ID_individual_id),
        ])
    Beacon_ID._ext = None
    
    #-----< BST-Configuration >-----#
    BST_Configuration = SEQ(name='BST-Configuration', mode=MODE_TYPE)
    _BST_Configuration_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _BST_Configuration_beacon = SEQ(name='beacon', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Beacon-ID')))
    _BST_Configuration_profile = INT(name='profile', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _BST_Configuration_mandatory_application_list = SEQ(name='mandatory-application-list', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Application-List')))
    BST_Configuration._cont = ASN1Dict([
        ('message-status', _BST_Configuration_message_status),
        ('beacon', _BST_Configuration_beacon),
        ('profile', _BST_Configuration_profile),
        ('mandatory-application-list', _BST_Configuration_mandatory_application_list),
        ])
    BST_Configuration._ext = None
    
    #-----< Time >-----#
    Time = SEQ(name='Time', mode=MODE_TYPE)
    _Time_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _Time_unix_time = INT(name='unix-time', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Time_milliseconds = INT(name='milliseconds', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Time._cont = ASN1Dict([
        ('message-status', _Time_message_status),
        ('unix-time', _Time_unix_time),
        ('milliseconds', _Time_milliseconds),
        ])
    Time._ext = None
    
    #-----< General-Log-Level >-----#
    General_Log_Level = SEQ(name='General-Log-Level', mode=MODE_TYPE)
    _General_Log_Level_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _General_Log_Level_log_level = INT(name='log-level', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    General_Log_Level._cont = ASN1Dict([
        ('message-status', _General_Log_Level_message_status),
        ('log-level', _General_Log_Level_log_level),
        ])
    General_Log_Level._ext = None
    
    #-----< Log-Category-Mode >-----#
    Log_Category_Mode = SEQ(name='Log-Category-Mode', mode=MODE_TYPE)
    _Log_Category_Mode_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _Log_Category_Mode_log_category = INT(name='log-category', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Log_Category_Mode_mode = INT(name='mode', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    Log_Category_Mode._cont = ASN1Dict([
        ('message-status', _Log_Category_Mode_message_status),
        ('log-category', _Log_Category_Mode_log_category),
        ('mode', _Log_Category_Mode_mode),
        ])
    Log_Category_Mode._ext = None
    
    #-----< Transaction-Status >-----#
    Transaction_Status = SEQ(name='Transaction-Status', mode=MODE_TYPE)
    _Transaction_Status_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Transaction_Status_transaction_status = INT(name='transaction-status', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Transaction_Status._cont = ASN1Dict([
        ('message-status', _Transaction_Status_message_status),
        ('transaction-status', _Transaction_Status_transaction_status),
        ])
    Transaction_Status._ext = None
    
    #-----< Echo >-----#
    Echo = SEQ(name='Echo', mode=MODE_TYPE)
    _Echo_length = INT(name='length', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Echo_data = OCT_STR(name='data', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Echo_data._const_sz = ASN1Set(rv=[500], rr=[], ev=None, er=[])
    Echo._cont = ASN1Dict([
        ('length', _Echo_length),
        ('data', _Echo_data),
        ])
    Echo._ext = None
    
    #-----< Communication-Log-Result >-----#
    Communication_Log_Result = SEQ(name='Communication-Log-Result', mode=MODE_TYPE)
    _Communication_Log_Result_link_identifier = INT(name='link-identifier', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Communication_Log_Result_trx_no = INT(name='trx-no', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Communication_Log_Result_data_age = INT(name='data-age', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Communication_Log_Result_angle_a = INT(name='angle-a', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Communication_Log_Result_angle_b = INT(name='angle-b', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Communication_Log_Result_angular_quality = INT(name='angular-quality', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Communication_Log_Result_signal_level_uplink = INT(name='signal-level-uplink', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Communication_Log_Result_frame_length = INT(name='frame-length', mode=MODE_TYPE, tag=(7, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Communication_Log_Result._cont = ASN1Dict([
        ('link-identifier', _Communication_Log_Result_link_identifier),
        ('trx-no', _Communication_Log_Result_trx_no),
        ('data-age', _Communication_Log_Result_data_age),
        ('angle-a', _Communication_Log_Result_angle_a),
        ('angle-b', _Communication_Log_Result_angle_b),
        ('angular-quality', _Communication_Log_Result_angular_quality),
        ('signal-level-uplink', _Communication_Log_Result_signal_level_uplink),
        ('frame-length', _Communication_Log_Result_frame_length),
        ])
    Communication_Log_Result._ext = None
    
    #-----< LiC-Status >-----#
    LiC_Status = SEQ(name='LiC-Status', mode=MODE_TYPE)
    _LiC_Status_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _LiC_Status_lic_status = SEQ_OF(name='lic-status', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __LiC_Status_lic_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _LiC_Status_lic_status._cont = __LiC_Status_lic_status__item_
    _LiC_Status_lic_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _LiC_Status_trx_1_status = SEQ_OF(name='trx-1-status', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __LiC_Status_trx_1_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _LiC_Status_trx_1_status._cont = __LiC_Status_trx_1_status__item_
    _LiC_Status_trx_1_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _LiC_Status_trx_2_status = SEQ_OF(name='trx-2-status', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __LiC_Status_trx_2_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _LiC_Status_trx_2_status._cont = __LiC_Status_trx_2_status__item_
    _LiC_Status_trx_2_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _LiC_Status_trx_3_status = SEQ_OF(name='trx-3-status', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __LiC_Status_trx_3_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _LiC_Status_trx_3_status._cont = __LiC_Status_trx_3_status__item_
    _LiC_Status_trx_3_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _LiC_Status_trx_4_status = SEQ_OF(name='trx-4-status', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __LiC_Status_trx_4_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _LiC_Status_trx_4_status._cont = __LiC_Status_trx_4_status__item_
    _LiC_Status_trx_4_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _LiC_Status_trx_5_status = SEQ_OF(name='trx-5-status', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __LiC_Status_trx_5_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _LiC_Status_trx_5_status._cont = __LiC_Status_trx_5_status__item_
    _LiC_Status_trx_5_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _LiC_Status_trx_6_status = SEQ_OF(name='trx-6-status', mode=MODE_TYPE, tag=(7, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __LiC_Status_trx_6_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _LiC_Status_trx_6_status._cont = __LiC_Status_trx_6_status__item_
    _LiC_Status_trx_6_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _LiC_Status_trx_7_status = SEQ_OF(name='trx-7-status', mode=MODE_TYPE, tag=(8, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __LiC_Status_trx_7_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _LiC_Status_trx_7_status._cont = __LiC_Status_trx_7_status__item_
    _LiC_Status_trx_7_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    _LiC_Status_trx_8_status = SEQ_OF(name='trx-8-status', mode=MODE_TYPE, tag=(9, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __LiC_Status_trx_8_status__item_ = INT(name='_item_', mode=MODE_TYPE)
    _LiC_Status_trx_8_status._cont = __LiC_Status_trx_8_status__item_
    _LiC_Status_trx_8_status._const_sz = ASN1Set(rv=[2], rr=[], ev=None, er=[])
    LiC_Status._cont = ASN1Dict([
        ('message-status', _LiC_Status_message_status),
        ('lic-status', _LiC_Status_lic_status),
        ('trx-1-status', _LiC_Status_trx_1_status),
        ('trx-2-status', _LiC_Status_trx_2_status),
        ('trx-3-status', _LiC_Status_trx_3_status),
        ('trx-4-status', _LiC_Status_trx_4_status),
        ('trx-5-status', _LiC_Status_trx_5_status),
        ('trx-6-status', _LiC_Status_trx_6_status),
        ('trx-7-status', _LiC_Status_trx_7_status),
        ('trx-8-status', _LiC_Status_trx_8_status),
        ])
    LiC_Status._ext = None
    
    #-----< LiC-Statistics >-----#
    LiC_Statistics = SEQ(name='LiC-Statistics', mode=MODE_TYPE)
    _LiC_Statistics_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _LiC_Statistics_module_id = INT(name='module-id', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _LiC_Statistics_number_of_parameters = INT(name='number-of-parameters', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _LiC_Statistics_parameter = SEQ_OF(name='parameter', mode=MODE_TYPE, tag=(3, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    __LiC_Statistics_parameter__item_ = INT(name='_item_', mode=MODE_TYPE)
    _LiC_Statistics_parameter._cont = __LiC_Statistics_parameter__item_
    _LiC_Statistics_parameter._const_sz = ASN1Set(rv=[40], rr=[], ev=None, er=[])
    LiC_Statistics._cont = ASN1Dict([
        ('message-status', _LiC_Statistics_message_status),
        ('module-id', _LiC_Statistics_module_id),
        ('number-of-parameters', _LiC_Statistics_number_of_parameters),
        ('parameter', _LiC_Statistics_parameter),
        ])
    LiC_Statistics._ext = None
    
    #-----< Status-Mode >-----#
    Status_Mode = SEQ(name='Status-Mode', mode=MODE_TYPE)
    _Status_Mode_message_status = INT(name='message-status', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), opt=True)
    _Status_Mode_mode = INT(name='mode', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _Status_Mode_interval = INT(name='interval', mode=MODE_TYPE, tag=(2, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    Status_Mode._cont = ASN1Dict([
        ('message-status', _Status_Mode_message_status),
        ('mode', _Status_Mode_mode),
        ('interval', _Status_Mode_interval),
        ])
    Status_Mode._ext = None
    
    #-----< LiC-Version >-----#
    LiC_Version = SEQ(name='LiC-Version', mode=MODE_TYPE)
    _LiC_Version_lic_serial_number = OCT_STR(name='lic-serial-number', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _LiC_Version_lic_serial_number._const_sz = ASN1Set(rv=[8], rr=[], ev=None, er=[])
    _LiC_Version_lic_sw_version = OCT_STR(name='lic-sw-version', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT))
    _LiC_Version_lic_sw_version._const_sz = ASN1Set(rv=[4], rr=[], ev=None, er=[])
    LiC_Version._cont = ASN1Dict([
        ('lic-serial-number', _LiC_Version_lic_serial_number),
        ('lic-sw-version', _LiC_Version_lic_sw_version),
        ])
    LiC_Version._ext = None
    
    #-----< Ops1955-Message-Types >-----#
    Ops1955_Message_Types = CHOICE(name='Ops1955-Message-Types', mode=MODE_TYPE)
    _Ops1955_Message_Types_action_request = SEQ(name='action-request', mode=MODE_TYPE, tag=(0, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Action-Request')))
    _Ops1955_Message_Types_action_confirmation = SEQ(name='action-confirmation', mode=MODE_TYPE, tag=(1, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Action-Confirmation')))
    _Ops1955_Message_Types_set_request = SEQ(name='set-request', mode=MODE_TYPE, tag=(4, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Set-Request')))
    _Ops1955_Message_Types_set_confirmation = SEQ(name='set-confirmation', mode=MODE_TYPE, tag=(5, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Set-Confirmation')))
    _Ops1955_Message_Types_get_request = SEQ(name='get-request', mode=MODE_TYPE, tag=(6, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Get-Request')))
    _Ops1955_Message_Types_get_confirmation = SEQ(name='get-confirmation', mode=MODE_TYPE, tag=(7, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Get-Confirmation')))
    _Ops1955_Message_Types_notify_application_beacon = SEQ(name='notify-application-beacon', mode=MODE_TYPE, tag=(12, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Notify-Application-Beacon')))
    _Ops1955_Message_Types_ready_application = SEQ(name='ready-application', mode=MODE_TYPE, tag=(13, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Ready-Application')))
    _Ops1955_Message_Types_notify_application_lost_message = SEQ(name='notify-application-lost-message', mode=MODE_TYPE, tag=(14, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Notify-Application-Lost-Message')))
    _Ops1955_Message_Types_forced_release = SEQ(name='forced-release', mode=MODE_TYPE, tag=(18, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Forced-Release')))
    _Ops1955_Message_Types_tis_ready_application1 = SEQ(name='tis-ready-application1', mode=MODE_TYPE, tag=(103, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Tis-Ready-Application')))
    _Ops1955_Message_Types_tis_ready_application2 = SEQ(name='tis-ready-application2', mode=MODE_TYPE, tag=(105, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Tis-Ready-Application')))
    _Ops1955_Message_Types_trx_status = SEQ(name='trx-status', mode=MODE_TYPE, tag=(1401, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-Status')))
    _Ops1955_Message_Types_trx_id = SEQ(name='trx-id', mode=MODE_TYPE, tag=(1402, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-ID')))
    _Ops1955_Message_Types_trx_internal_humidity = SEQ(name='trx-internal-humidity', mode=MODE_TYPE, tag=(1403, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-Internal-Humidity')))
    _Ops1955_Message_Types_trx_internal_temperature = SEQ(name='trx-internal-temperature', mode=MODE_TYPE, tag=(1404, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-Internal-Temperature')))
    _Ops1955_Message_Types_trx_my_power_mode = SEQ(name='trx-my-power-mode', mode=MODE_TYPE, tag=(1405, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-My-Power-Mode')))
    _Ops1955_Message_Types_trx_carrier_frequency1 = SEQ(name='trx-carrier-frequency1', mode=MODE_TYPE, tag=(1406, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-Carrier-Frequency')))
    _Ops1955_Message_Types_trx_carrier_frequency2 = SEQ(name='trx-carrier-frequency2', mode=MODE_TYPE, tag=(1415, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-Carrier-Frequency')))
    _Ops1955_Message_Types_trx_uplink_parameters = SEQ(name='trx-uplink-parameters', mode=MODE_TYPE, tag=(1407, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-Uplink-Parameters')))
    _Ops1955_Message_Types_trx_output_power1 = SEQ(name='trx-output-power1', mode=MODE_TYPE, tag=(1408, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-Output-Power')))
    _Ops1955_Message_Types_trx_output_power2 = SEQ(name='trx-output-power2', mode=MODE_TYPE, tag=(1416, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-Output-Power')))
    _Ops1955_Message_Types_trx_echo = SEQ(name='trx-echo', mode=MODE_TYPE, tag=(1414, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-Echo')))
    _Ops1955_Message_Types_trx_set_ui_control = SEQ(name='trx-set-ui-control', mode=MODE_TYPE, tag=(1420, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-Set-UI-Control')))
    _Ops1955_Message_Types_trx_ui_status1 = SEQ(name='trx-ui-status1', mode=MODE_TYPE, tag=(1421, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-UI-Status')))
    _Ops1955_Message_Types_trx_ui_status2 = SEQ(name='trx-ui-status2', mode=MODE_TYPE, tag=(1422, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-UI-Status')))
    _Ops1955_Message_Types_trx_ui_status3 = SEQ(name='trx-ui-status3', mode=MODE_TYPE, tag=(1423, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-UI-Status')))
    _Ops1955_Message_Types_trx_general_purpose = SEQ(name='trx-general-purpose', mode=MODE_TYPE, tag=(1500, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-General-Purpose')))
    _Ops1955_Message_Types_trx_extended_output_power = SEQ(name='trx-extended-output-power', mode=MODE_TYPE, tag=(1506, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-Extended-Output-Power')))
    _Ops1955_Message_Types_trx_read_rf_param1 = SEQ(name='trx-read-rf-param1', mode=MODE_TYPE, tag=(1516, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-Read-RF-Param')))
    _Ops1955_Message_Types_trx_read_rf_param2 = SEQ(name='trx-read-rf-param2', mode=MODE_TYPE, tag=(1517, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'TRX-Read-RF-Param')))
    _Ops1955_Message_Types_lic_nalm_behaviour1 = SEQ(name='lic-nalm-behaviour1', mode=MODE_TYPE, tag=(2408, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Lic-Nalm-Behaviour')))
    _Ops1955_Message_Types_lic_nalm_behaviour2 = SEQ(name='lic-nalm-behaviour2', mode=MODE_TYPE, tag=(2409, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Lic-Nalm-Behaviour')))
    _Ops1955_Message_Types_lic_pdu_no_behaviour1 = SEQ(name='lic-pdu-no-behaviour1', mode=MODE_TYPE, tag=(2410, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Lic-PDU-No-Behaviour')))
    _Ops1955_Message_Types_lic_pdu_no_behaviour2 = SEQ(name='lic-pdu-no-behaviour2', mode=MODE_TYPE, tag=(2411, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Lic-PDU-No-Behaviour')))
    _Ops1955_Message_Types_lic_l7_ack_mode1 = SEQ(name='lic-l7-ack-mode1', mode=MODE_TYPE, tag=(2412, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Lic-L7-Ack-Mode')))
    _Ops1955_Message_Types_lic_l7_ack_mode2 = SEQ(name='lic-l7-ack-mode2', mode=MODE_TYPE, tag=(2413, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Lic-L7-Ack-Mode')))
    _Ops1955_Message_Types_lic_private_uplink_window_time1 = SEQ(name='lic-private-uplink-window-time1', mode=MODE_TYPE, tag=(2414, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Lic-Private-Uplink-Window-Time')))
    _Ops1955_Message_Types_lic_private_uplink_window_time2 = SEQ(name='lic-private-uplink-window-time2', mode=MODE_TYPE, tag=(2415, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Lic-Private-Uplink-Window-Time')))
    _Ops1955_Message_Types_lic_slow_data_behaviour1 = SEQ(name='lic-slow-data-behaviour1', mode=MODE_TYPE, tag=(2416, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Lic-Slow-Data-Behaviour')))
    _Ops1955_Message_Types_lic_slow_data_behaviour2 = SEQ(name='lic-slow-data-behaviour2', mode=MODE_TYPE, tag=(2417, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Lic-Slow-Data-Behaviour')))
    _Ops1955_Message_Types_lic_release_retransmissions1 = SEQ(name='lic-release-retransmissions1', mode=MODE_TYPE, tag=(2418, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Lic-Release-Retransmissions')))
    _Ops1955_Message_Types_lic_release_retransmissions2 = SEQ(name='lic-release-retransmissions2', mode=MODE_TYPE, tag=(2419, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Lic-Release-Retransmissions')))
    _Ops1955_Message_Types_lic_lid_cleanup_mode1 = SEQ(name='lic-lid-cleanup-mode1', mode=MODE_TYPE, tag=(2420, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Lic-LID-Cleanup-Mode')))
    _Ops1955_Message_Types_lic_lid_cleanup_mode2 = SEQ(name='lic-lid-cleanup-mode2', mode=MODE_TYPE, tag=(2421, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Lic-LID-Cleanup-Mode')))
    _Ops1955_Message_Types_dsrc_link_mode1 = SEQ(name='dsrc-link-mode1', mode=MODE_TYPE, tag=(2450, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'DSRC-Link-Mode')))
    _Ops1955_Message_Types_dsrc_link_mode2 = SEQ(name='dsrc-link-mode2', mode=MODE_TYPE, tag=(2451, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'DSRC-Link-Mode')))
    _Ops1955_Message_Types_dsrc_configuration = SEQ(name='dsrc-configuration', mode=MODE_TYPE, tag=(2455, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'DSRC-Configuration')))
    _Ops1955_Message_Types_bst_configuration1 = SEQ(name='bst-configuration1', mode=MODE_TYPE, tag=(2457, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'BST-Configuration')))
    _Ops1955_Message_Types_bst_configuration2 = SEQ(name='bst-configuration2', mode=MODE_TYPE, tag=(2458, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'BST-Configuration')))
    _Ops1955_Message_Types_time1 = SEQ(name='time1', mode=MODE_TYPE, tag=(2459, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Time')))
    _Ops1955_Message_Types_time2 = SEQ(name='time2', mode=MODE_TYPE, tag=(2460, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Time')))
    _Ops1955_Message_Types_general_log_level1 = SEQ(name='general-log-level1', mode=MODE_TYPE, tag=(2463, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'General-Log-Level')))
    _Ops1955_Message_Types_general_log_level2 = SEQ(name='general-log-level2', mode=MODE_TYPE, tag=(2464, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'General-Log-Level')))
    _Ops1955_Message_Types_log_category_mode1 = SEQ(name='log-category-mode1', mode=MODE_TYPE, tag=(2465, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Log-Category-Mode')))
    _Ops1955_Message_Types_log_category_mode2 = SEQ(name='log-category-mode2', mode=MODE_TYPE, tag=(2466, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Log-Category-Mode')))
    _Ops1955_Message_Types_transaction_status1 = SEQ(name='transaction-status1', mode=MODE_TYPE, tag=(2482, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Transaction-Status')))
    _Ops1955_Message_Types_transaction_status2 = SEQ(name='transaction-status2', mode=MODE_TYPE, tag=(2483, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Transaction-Status')))
    _Ops1955_Message_Types_echo = SEQ(name='echo', mode=MODE_TYPE, tag=(2605, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Echo')))
    _Ops1955_Message_Types_communication_log_result = SEQ(name='communication-log-result', mode=MODE_TYPE, tag=(2650, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Communication-Log-Result')))
    _Ops1955_Message_Types_lic_status1 = SEQ(name='lic-status1', mode=MODE_TYPE, tag=(2651, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'LiC-Status')))
    _Ops1955_Message_Types_lic_status2 = SEQ(name='lic-status2', mode=MODE_TYPE, tag=(2752, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'LiC-Status')))
    _Ops1955_Message_Types_lic_statistics = SEQ(name='lic-statistics', mode=MODE_TYPE, tag=(2751, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'LiC-Statistics')))
    _Ops1955_Message_Types_status_mode1 = SEQ(name='status-mode1', mode=MODE_TYPE, tag=(2753, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Status-Mode')))
    _Ops1955_Message_Types_status_mode2 = SEQ(name='status-mode2', mode=MODE_TYPE, tag=(2754, TAG_CONTEXT_SPEC, TAG_IMPLICIT), typeref=ASN1RefType(('KapschOps1955Message', 'Status-Mode')))
    Ops1955_Message_Types._cont = ASN1Dict([
        ('action-request', _Ops1955_Message_Types_action_request),
        ('action-confirmation', _Ops1955_Message_Types_action_confirmation),
        ('set-request', _Ops1955_Message_Types_set_request),
        ('set-confirmation', _Ops1955_Message_Types_set_confirmation),
        ('get-request', _Ops1955_Message_Types_get_request),
        ('get-confirmation', _Ops1955_Message_Types_get_confirmation),
        ('notify-application-beacon', _Ops1955_Message_Types_notify_application_beacon),
        ('ready-application', _Ops1955_Message_Types_ready_application),
        ('notify-application-lost-message', _Ops1955_Message_Types_notify_application_lost_message),
        ('forced-release', _Ops1955_Message_Types_forced_release),
        ('tis-ready-application1', _Ops1955_Message_Types_tis_ready_application1),
        ('tis-ready-application2', _Ops1955_Message_Types_tis_ready_application2),
        ('trx-status', _Ops1955_Message_Types_trx_status),
        ('trx-id', _Ops1955_Message_Types_trx_id),
        ('trx-internal-humidity', _Ops1955_Message_Types_trx_internal_humidity),
        ('trx-internal-temperature', _Ops1955_Message_Types_trx_internal_temperature),
        ('trx-my-power-mode', _Ops1955_Message_Types_trx_my_power_mode),
        ('trx-carrier-frequency1', _Ops1955_Message_Types_trx_carrier_frequency1),
        ('trx-carrier-frequency2', _Ops1955_Message_Types_trx_carrier_frequency2),
        ('trx-uplink-parameters', _Ops1955_Message_Types_trx_uplink_parameters),
        ('trx-output-power1', _Ops1955_Message_Types_trx_output_power1),
        ('trx-output-power2', _Ops1955_Message_Types_trx_output_power2),
        ('trx-echo', _Ops1955_Message_Types_trx_echo),
        ('trx-set-ui-control', _Ops1955_Message_Types_trx_set_ui_control),
        ('trx-ui-status1', _Ops1955_Message_Types_trx_ui_status1),
        ('trx-ui-status2', _Ops1955_Message_Types_trx_ui_status2),
        ('trx-ui-status3', _Ops1955_Message_Types_trx_ui_status3),
        ('trx-general-purpose', _Ops1955_Message_Types_trx_general_purpose),
        ('trx-extended-output-power', _Ops1955_Message_Types_trx_extended_output_power),
        ('trx-read-rf-param1', _Ops1955_Message_Types_trx_read_rf_param1),
        ('trx-read-rf-param2', _Ops1955_Message_Types_trx_read_rf_param2),
        ('lic-nalm-behaviour1', _Ops1955_Message_Types_lic_nalm_behaviour1),
        ('lic-nalm-behaviour2', _Ops1955_Message_Types_lic_nalm_behaviour2),
        ('lic-pdu-no-behaviour1', _Ops1955_Message_Types_lic_pdu_no_behaviour1),
        ('lic-pdu-no-behaviour2', _Ops1955_Message_Types_lic_pdu_no_behaviour2),
        ('lic-l7-ack-mode1', _Ops1955_Message_Types_lic_l7_ack_mode1),
        ('lic-l7-ack-mode2', _Ops1955_Message_Types_lic_l7_ack_mode2),
        ('lic-private-uplink-window-time1', _Ops1955_Message_Types_lic_private_uplink_window_time1),
        ('lic-private-uplink-window-time2', _Ops1955_Message_Types_lic_private_uplink_window_time2),
        ('lic-slow-data-behaviour1', _Ops1955_Message_Types_lic_slow_data_behaviour1),
        ('lic-slow-data-behaviour2', _Ops1955_Message_Types_lic_slow_data_behaviour2),
        ('lic-release-retransmissions1', _Ops1955_Message_Types_lic_release_retransmissions1),
        ('lic-release-retransmissions2', _Ops1955_Message_Types_lic_release_retransmissions2),
        ('lic-lid-cleanup-mode1', _Ops1955_Message_Types_lic_lid_cleanup_mode1),
        ('lic-lid-cleanup-mode2', _Ops1955_Message_Types_lic_lid_cleanup_mode2),
        ('dsrc-link-mode1', _Ops1955_Message_Types_dsrc_link_mode1),
        ('dsrc-link-mode2', _Ops1955_Message_Types_dsrc_link_mode2),
        ('dsrc-configuration', _Ops1955_Message_Types_dsrc_configuration),
        ('bst-configuration1', _Ops1955_Message_Types_bst_configuration1),
        ('bst-configuration2', _Ops1955_Message_Types_bst_configuration2),
        ('time1', _Ops1955_Message_Types_time1),
        ('time2', _Ops1955_Message_Types_time2),
        ('general-log-level1', _Ops1955_Message_Types_general_log_level1),
        ('general-log-level2', _Ops1955_Message_Types_general_log_level2),
        ('log-category-mode1', _Ops1955_Message_Types_log_category_mode1),
        ('log-category-mode2', _Ops1955_Message_Types_log_category_mode2),
        ('transaction-status1', _Ops1955_Message_Types_transaction_status1),
        ('transaction-status2', _Ops1955_Message_Types_transaction_status2),
        ('echo', _Ops1955_Message_Types_echo),
        ('communication-log-result', _Ops1955_Message_Types_communication_log_result),
        ('lic-status1', _Ops1955_Message_Types_lic_status1),
        ('lic-status2', _Ops1955_Message_Types_lic_status2),
        ('lic-statistics', _Ops1955_Message_Types_lic_statistics),
        ('status-mode1', _Ops1955_Message_Types_status_mode1),
        ('status-mode2', _Ops1955_Message_Types_status_mode2),
        ])
    Ops1955_Message_Types._ext = None
    
    _all_ = [
        _Octetstring_no_of_octets,
        __Octetstring_octet__item_,
        _Octetstring_octet,
        Octetstring,
        _Container_integer,
        _Container_octetstring,
        Container,
        _Action_Request_flow_control_priority,
        _Action_Request_link_id,
        _Action_Request_flow_control,
        _Action_Request_access_credentials_bit_map,
        _Action_Request_action_parameter_bit_map,
        _Action_Request_mode,
        _Action_Request_element_id,
        _Action_Request_access_credentials,
        _Action_Request_action_parameter,
        Action_Request,
        _Action_Confirmation_link_id,
        _Action_Confirmation_response_parameter_bit_map,
        _Action_Confirmation_return_status_bit_map,
        _Action_Confirmation_element_id,
        _Action_Confirmation_response_parameter,
        _Action_Confirmation_return_status,
        _Action_Confirmation_instance,
        Action_Confirmation,
        _Attribute_attribute_id,
        _Attribute_attribute_choice,
        _Attribute_container,
        Attribute,
        _Attribute_List_no_of_attributes,
        __Attribute_List_attribute__item_,
        _Attribute_List_attribute,
        Attribute_List,
        _Set_Request_flow_control_priority,
        _Set_Request_link_id,
        _Set_Request_flow_control,
        _Set_Request_access_credentials_bit_map,
        _Set_Request_mode,
        _Set_Request_element_id,
        _Set_Request_access_credentials,
        _Set_Request_attribute_list,
        Set_Request,
        _Set_Confirmation_link_id,
        _Set_Confirmation_return_status_bit_map,
        _Set_Confirmation_element_id,
        _Set_Confirmation_return_status,
        _Set_Confirmation_instance,
        Set_Confirmation,
        _Attribute_ID_List_no_of_attribute_ids,
        __Attribute_ID_List_attribute_id__item_,
        _Attribute_ID_List_attribute_id,
        Attribute_ID_List,
        _Get_Request_flow_control_priority,
        _Get_Request_link_id,
        _Get_Request_flow_control,
        _Get_Request_access_credentials_bit_map,
        _Get_Request_element_id,
        _Get_Request_access_credentials,
        _Get_Request_attribute_id_list,
        Get_Request,
        _Get_Confirmation_link_id,
        _Get_Confirmation_attribute_list_bit_map,
        _Get_Confirmation_return_status_bit_map,
        _Get_Confirmation_element_id,
        _Get_Confirmation_attribute_list,
        _Get_Confirmation_return_status,
        _Get_Confirmation_instance,
        Get_Confirmation,
        _Application_element_id_bit_map,
        _Application_parameter_bit_map,
        _Application_application_id,
        _Application_element_id,
        _Application_parameter,
        Application,
        _Application_List_no_of_applications,
        __Application_List_application__item_,
        _Application_List_application,
        Application_List,
        _OBE_Configuration_equipment_class,
        _OBE_Configuration_manufacturer_id,
        _OBE_Configuration_obe_status,
        OBE_Configuration,
        _Notify_Application_Beacon_trx_no,
        _Notify_Application_Beacon_link_id,
        _Notify_Application_Beacon_application_list,
        _Notify_Application_Beacon_obe_configuration,
        Notify_Application_Beacon,
        _Ready_Application_flow_control_priority,
        _Ready_Application_application_id,
        _Ready_Application_link_id,
        Ready_Application,
        _Notify_Application_Lost_Message_link_id,
        _Notify_Application_Lost_Message_value,
        Notify_Application_Lost_Message,
        _Forced_Release_application_id,
        _Forced_Release_link_id,
        Forced_Release,
        _Tis_Ready_Application_flow_control_priority,
        _Tis_Ready_Application_application_id,
        _Tis_Ready_Application_link_id,
        _Tis_Ready_Application_eid,
        Tis_Ready_Application,
        _TRX_Status_instance,
        __TRX_Status_status__item_,
        _TRX_Status_status,
        _TRX_Status_trx_mode,
        TRX_Status,
        _TRX_ID_instance,
        __TRX_ID_status__item_,
        _TRX_ID_status,
        __TRX_ID_trx_id__item_,
        _TRX_ID_trx_id,
        __TRX_ID_hwid__item_,
        _TRX_ID_hwid,
        __TRX_ID_swid__item_,
        _TRX_ID_swid,
        TRX_ID,
        _TRX_Internal_Humidity_instance,
        __TRX_Internal_Humidity_status__item_,
        _TRX_Internal_Humidity_status,
        _TRX_Internal_Humidity_humid,
        TRX_Internal_Humidity,
        _TRX_Internal_Temperature_instance,
        __TRX_Internal_Temperature_status__item_,
        _TRX_Internal_Temperature_status,
        _TRX_Internal_Temperature_temp,
        TRX_Internal_Temperature,
        _TRX_My_Power_Mode_instance,
        _TRX_My_Power_Mode_mode,
        TRX_My_Power_Mode,
        _TRX_Carrier_Frequency_instance,
        __TRX_Carrier_Frequency_status__item_,
        _TRX_Carrier_Frequency_status,
        _TRX_Carrier_Frequency_cfq,
        TRX_Carrier_Frequency,
        _TRX_Uplink_Parameters_instance,
        _TRX_Uplink_Parameters_upl,
        TRX_Uplink_Parameters,
        _TRX_Output_Power_instance,
        __TRX_Output_Power_status__item_,
        _TRX_Output_Power_status,
        _TRX_Output_Power_spw,
        TRX_Output_Power,
        _TRX_Echo_instance,
        _TRX_Echo_data,
        _TRX_Echo_length,
        TRX_Echo,
        _UI_Control_OPS1925_mode,
        _UI_Control_OPS1925_green_led,
        _UI_Control_OPS1925_orange_led,
        _UI_Control_OPS1925_red_led,
        UI_Control_OPS1925,
        _UI_Control_OPS1955_red,
        _UI_Control_OPS1955_green,
        _UI_Control_OPS1955_blue,
        UI_Control_OPS1955,
        _TRX_Set_UI_Control_instance,
        __TRX_Set_UI_Control_status__item_,
        _TRX_Set_UI_Control_status,
        _TRX_Set_UI_Control_uitype,
        _TRX_Set_UI_Control_ops1925,
        _TRX_Set_UI_Control_ops1955,
        TRX_Set_UI_Control,
        _TRX_Read_UI_Control_instance,
        __TRX_Read_UI_Control_status__item_,
        _TRX_Read_UI_Control_status,
        _TRX_Read_UI_Control_uitype,
        _TRX_Read_UI_Control_mode,
        _TRX_Read_UI_Control_ops1925,
        _TRX_Read_UI_Control_ops1955,
        TRX_Read_UI_Control,
        _TRX_UI_Status_instance,
        __TRX_UI_Status_status__item_,
        _TRX_UI_Status_status,
        _TRX_UI_Status_uitype,
        _TRX_UI_Status_sensors,
        TRX_UI_Status,
        _TRX_General_Purpose_instance,
        _TRX_General_Purpose_password,
        _TRX_General_Purpose_genid,
        _TRX_General_Purpose_genda_genre,
        __TRX_General_Purpose_status__item_,
        _TRX_General_Purpose_status,
        _TRX_General_Purpose_length,
        TRX_General_Purpose,
        _TRX_Extended_Output_Power_instance,
        _TRX_Extended_Output_Power_password,
        _TRX_Extended_Output_Power_spw,
        TRX_Extended_Output_Power,
        _TRX_Set_RF_Param_instance,
        _TRX_Set_RF_Param_password,
        _TRX_Set_RF_Param_id,
        _TRX_Set_RF_Param_data,
        TRX_Set_RF_Param,
        _TRX_Read_RF_Param_instance,
        _TRX_Read_RF_Param_password,
        _TRX_Read_RF_Param_id1,
        _TRX_Read_RF_Param_id2,
        _TRX_Read_RF_Param_data,
        _TRX_Read_RF_Param_length,
        TRX_Read_RF_Param,
        _Lic_Nalm_Behaviour_message_status,
        _Lic_Nalm_Behaviour_behaviour,
        Lic_Nalm_Behaviour,
        _Lic_PDU_No_Behaviour_message_status,
        _Lic_PDU_No_Behaviour_behaviour,
        Lic_PDU_No_Behaviour,
        _Lic_L7_Ack_Mode_message_status,
        _Lic_L7_Ack_Mode_mode,
        Lic_L7_Ack_Mode,
        _Lic_Private_Uplink_Window_Time_message_status,
        _Lic_Private_Uplink_Window_Time_uplink_window_time,
        Lic_Private_Uplink_Window_Time,
        _Lic_Slow_Data_Behaviour_message_status,
        _Lic_Slow_Data_Behaviour_slow_data_behaviour,
        Lic_Slow_Data_Behaviour,
        _Lic_Release_Retransmissions_message_status,
        _Lic_Release_Retransmissions_retransmissions,
        Lic_Release_Retransmissions,
        _Lic_LID_Cleanup_Mode_message_status,
        _Lic_LID_Cleanup_Mode_lid_cleanup_mode,
        Lic_LID_Cleanup_Mode,
        _DSRC_Link_Mode_message_status,
        _DSRC_Link_Mode_mode,
        DSRC_Link_Mode,
        _DSRC_Configuration_message_status,
        _DSRC_Configuration_trx_position,
        _DSRC_Configuration_bst_mode,
        _DSRC_Configuration_low_priority_bst_cycle_time,
        _DSRC_Configuration_high_priority_bst_cycle_time,
        _DSRC_Configuration_max_cycle_time_llc_retransmissions_level_1,
        _DSRC_Configuration_max_cycle_time_llc_retransmissions_level_2,
        _DSRC_Configuration_max_cycle_time_llc_retransmissions_level_3,
        _DSRC_Configuration_max_cycle_time_llc_retransmissions_level_4,
        _DSRC_Configuration_max_nr_llc_retransmissions_level_1,
        _DSRC_Configuration_max_nr_llc_retransmissions_level_2,
        _DSRC_Configuration_max_nr_llc_retransmissions_level_3,
        _DSRC_Configuration_max_nr_llc_retransmissions_level_4,
        _DSRC_Configuration_max_nr_mac_retransmissions,
        DSRC_Configuration,
        _Beacon_ID_manufacturer_id,
        _Beacon_ID_individual_id,
        Beacon_ID,
        _BST_Configuration_message_status,
        _BST_Configuration_beacon,
        _BST_Configuration_profile,
        _BST_Configuration_mandatory_application_list,
        BST_Configuration,
        _Time_message_status,
        _Time_unix_time,
        _Time_milliseconds,
        Time,
        _General_Log_Level_message_status,
        _General_Log_Level_log_level,
        General_Log_Level,
        _Log_Category_Mode_message_status,
        _Log_Category_Mode_log_category,
        _Log_Category_Mode_mode,
        Log_Category_Mode,
        _Transaction_Status_message_status,
        _Transaction_Status_transaction_status,
        Transaction_Status,
        _Echo_length,
        _Echo_data,
        Echo,
        _Communication_Log_Result_link_identifier,
        _Communication_Log_Result_trx_no,
        _Communication_Log_Result_data_age,
        _Communication_Log_Result_angle_a,
        _Communication_Log_Result_angle_b,
        _Communication_Log_Result_angular_quality,
        _Communication_Log_Result_signal_level_uplink,
        _Communication_Log_Result_frame_length,
        Communication_Log_Result,
        _LiC_Status_message_status,
        __LiC_Status_lic_status__item_,
        _LiC_Status_lic_status,
        __LiC_Status_trx_1_status__item_,
        _LiC_Status_trx_1_status,
        __LiC_Status_trx_2_status__item_,
        _LiC_Status_trx_2_status,
        __LiC_Status_trx_3_status__item_,
        _LiC_Status_trx_3_status,
        __LiC_Status_trx_4_status__item_,
        _LiC_Status_trx_4_status,
        __LiC_Status_trx_5_status__item_,
        _LiC_Status_trx_5_status,
        __LiC_Status_trx_6_status__item_,
        _LiC_Status_trx_6_status,
        __LiC_Status_trx_7_status__item_,
        _LiC_Status_trx_7_status,
        __LiC_Status_trx_8_status__item_,
        _LiC_Status_trx_8_status,
        LiC_Status,
        _LiC_Statistics_message_status,
        _LiC_Statistics_module_id,
        _LiC_Statistics_number_of_parameters,
        __LiC_Statistics_parameter__item_,
        _LiC_Statistics_parameter,
        LiC_Statistics,
        _Status_Mode_message_status,
        _Status_Mode_mode,
        _Status_Mode_interval,
        Status_Mode,
        _LiC_Version_lic_serial_number,
        _LiC_Version_lic_sw_version,
        LiC_Version,
        _Ops1955_Message_Types_action_request,
        _Ops1955_Message_Types_action_confirmation,
        _Ops1955_Message_Types_set_request,
        _Ops1955_Message_Types_set_confirmation,
        _Ops1955_Message_Types_get_request,
        _Ops1955_Message_Types_get_confirmation,
        _Ops1955_Message_Types_notify_application_beacon,
        _Ops1955_Message_Types_ready_application,
        _Ops1955_Message_Types_notify_application_lost_message,
        _Ops1955_Message_Types_forced_release,
        _Ops1955_Message_Types_tis_ready_application1,
        _Ops1955_Message_Types_tis_ready_application2,
        _Ops1955_Message_Types_trx_status,
        _Ops1955_Message_Types_trx_id,
        _Ops1955_Message_Types_trx_internal_humidity,
        _Ops1955_Message_Types_trx_internal_temperature,
        _Ops1955_Message_Types_trx_my_power_mode,
        _Ops1955_Message_Types_trx_carrier_frequency1,
        _Ops1955_Message_Types_trx_carrier_frequency2,
        _Ops1955_Message_Types_trx_uplink_parameters,
        _Ops1955_Message_Types_trx_output_power1,
        _Ops1955_Message_Types_trx_output_power2,
        _Ops1955_Message_Types_trx_echo,
        _Ops1955_Message_Types_trx_set_ui_control,
        _Ops1955_Message_Types_trx_ui_status1,
        _Ops1955_Message_Types_trx_ui_status2,
        _Ops1955_Message_Types_trx_ui_status3,
        _Ops1955_Message_Types_trx_general_purpose,
        _Ops1955_Message_Types_trx_extended_output_power,
        _Ops1955_Message_Types_trx_read_rf_param1,
        _Ops1955_Message_Types_trx_read_rf_param2,
        _Ops1955_Message_Types_lic_nalm_behaviour1,
        _Ops1955_Message_Types_lic_nalm_behaviour2,
        _Ops1955_Message_Types_lic_pdu_no_behaviour1,
        _Ops1955_Message_Types_lic_pdu_no_behaviour2,
        _Ops1955_Message_Types_lic_l7_ack_mode1,
        _Ops1955_Message_Types_lic_l7_ack_mode2,
        _Ops1955_Message_Types_lic_private_uplink_window_time1,
        _Ops1955_Message_Types_lic_private_uplink_window_time2,
        _Ops1955_Message_Types_lic_slow_data_behaviour1,
        _Ops1955_Message_Types_lic_slow_data_behaviour2,
        _Ops1955_Message_Types_lic_release_retransmissions1,
        _Ops1955_Message_Types_lic_release_retransmissions2,
        _Ops1955_Message_Types_lic_lid_cleanup_mode1,
        _Ops1955_Message_Types_lic_lid_cleanup_mode2,
        _Ops1955_Message_Types_dsrc_link_mode1,
        _Ops1955_Message_Types_dsrc_link_mode2,
        _Ops1955_Message_Types_dsrc_configuration,
        _Ops1955_Message_Types_bst_configuration1,
        _Ops1955_Message_Types_bst_configuration2,
        _Ops1955_Message_Types_time1,
        _Ops1955_Message_Types_time2,
        _Ops1955_Message_Types_general_log_level1,
        _Ops1955_Message_Types_general_log_level2,
        _Ops1955_Message_Types_log_category_mode1,
        _Ops1955_Message_Types_log_category_mode2,
        _Ops1955_Message_Types_transaction_status1,
        _Ops1955_Message_Types_transaction_status2,
        _Ops1955_Message_Types_echo,
        _Ops1955_Message_Types_communication_log_result,
        _Ops1955_Message_Types_lic_status1,
        _Ops1955_Message_Types_lic_status2,
        _Ops1955_Message_Types_lic_statistics,
        _Ops1955_Message_Types_status_mode1,
        _Ops1955_Message_Types_status_mode2,
        Ops1955_Message_Types,
    ]

init_modules(KapschOps1955Message)
